FROM node:26.10.0

# Instalar Angular CLI de forma global
RUN npm install -g @angular/cli@22.2.0

# Definimos la ruta exacta de la app
WORKDIR /usr/src/web

# Exponer el puerto de Angular
EXPOSE 4200

